"""
Django settings for location_erp project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import unquote, urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (os.getenv('SECRET_KEY') or '').strip() or (
    'django-insecure-7ot8cpvx!p+35fnrxix^g9-g$rv4yz6py5akoh)6-^vkr(8g7p'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

_allowed = os.getenv('ALLOWED_HOSTS', '').strip()
ALLOWED_HOSTS = (
    [h.strip() for h in _allowed.split(',') if h.strip()]
    if _allowed
    else ['localhost', '127.0.0.1', '0.0.0.0']
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_extensions',
    'storages',
    'auditlog',
    'audit',
    'authentication',
    'biens',
    'clients',
    'contrats',
    'paiements',
    'depenses',
    'analytics',
    'notifications',
    'documents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'location_erp.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'location_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'location_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_database_url = os.getenv('DATABASE_URL', '').strip()
_postgres_host = os.getenv('POSTGRES_HOST', '').strip()

if _database_url and _database_url.split(':', 1)[0].lower().startswith('postgres'):
    _u = urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (_u.path or '/').lstrip('/') or 'postgres',
            'USER': unquote(_u.username or 'postgres'),
            'PASSWORD': unquote(_u.password or ''),
            'HOST': _u.hostname or 'localhost',
            'PORT': str(_u.port or 5432),
        }
    }
elif _postgres_host:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'location_erp'),
            'USER': os.getenv('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
            'HOST': _postgres_host,
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# CORS settings
_cors = os.getenv('CORS_ALLOWED_ORIGINS', '').strip()
if _cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3001',
    ]

_csrf = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = (
    [o.strip() for o in _csrf.split(',') if o.strip()]
    if _csrf
    else list(CORS_ALLOWED_ORIGINS)
)

# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Dakar'

# Custom user model
AUTH_USER_MODEL = 'authentication.Utilisateur'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# MinIO S3 Storage Configuration
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # Configuration MinIO/S3
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', 'minioadmin')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', 'minioadmin123')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'location-erp')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL', 'http://localhost:9000')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN', 'localhost:9000')
    _s3_scheme = 'https' if AWS_S3_ENDPOINT_URL.lower().startswith('https://') else 'http'
    
    # Configuration Django-Storages
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    
    # URLs S3 (schéma aligné sur l'endpoint pour éviter du mixed content en dev HTTP)
    MEDIA_URL = f'{_s3_scheme}://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STORAGE_BUCKET_NAME}/media/'
    STATIC_URL = f'{_s3_scheme}://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STORAGE_BUCKET_NAME}/static/'
    
    # Configuration S3 avancée
    S3_USE_THREADS = True
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_BUCKET_AUTH = False
    AWS_S3_VERIFY = os.getenv(
        'AWS_S3_VERIFY',
        'false' if AWS_S3_ENDPOINT_URL.lower().startswith('http://') else 'true',
    ).lower() in ('1', 'true', 'yes')
    
    # Configuration des headers CORS pour S3
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    
    # Configuration des types de fichiers autorisés
    AWS_PRELOAD_METADATA = True
    
else:
    # Configuration locale (fallback)
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STATIC_URL = '/static/'
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'

# Static files configuration
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Spectacular API Documentation settings
SPECTACULAR_SETTINGS = {
    'DEFAULT_GENERATOR_CLASS': 'location_erp.schema_generator.SchemaGenerator',
    'TITLE': 'ERP Location Immobilière API',
    'DESCRIPTION': 'API complète pour la gestion de location immobilière',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_DIST': 'https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.17.2',
    'SWAGGER_UI_FAVICON_HREF': 'https://fastapi.tiangolo.com/img/favicon.png',
    'REDOC_DIST': 'https://cdn.jsdelivr.net/npm/redoc@2.1.3/bundles/redoc.standalone.js',
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Développement'},
        {'url': 'https://your-domain.com', 'description': 'Production'},
    ],
    'TAGS': [
        {'name': 'Authentication', 'description': 'Gestion des utilisateurs et authentification'},
        {'name': 'Biens', 'description': 'Gestion des biens immobiliers'},
        {'name': 'Clients', 'description': 'Gestion des clients/locataires'},
        {'name': 'Contrats', 'description': 'Gestion des contrats de location'},
        {'name': 'Paiements', 'description': 'Suivi des paiements et échéances'},
        {'name': 'Dépenses', 'description': 'Gestion des dépenses'},
        {'name': 'Analytics', 'description': 'Analyse financière et rapports'},
    ],
    'SECURITY': [
        {'bearerAuth': []}
    ],
    'COMPONENT_SECURITY_REQUEST': {
        'bearerAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        }
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
        'tryItOutEnabled': True,
    },
    # Référencer les listes de choix (pas le champ `statut`, qui est un DeferredAttribute)
    'ENUM_NAME_OVERRIDES': {
        'BienStatutEnum': 'biens.models.Bien.STATUT_CHOICES',
        'ContratStatutEnum': 'contrats.models.Contrat.STATUT_CHOICES',
        'PaiementStatutEnum': 'paiements.models.Paiement.STATUT_CHOICES',
    },
}

# Audit and Logging Configuration
AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_FIELDS = ['last_login', 'password', 'created_at', 'updated_at']
# Exclure SecurityEvent du tracking pour éviter les erreurs avec changes_text
AUDITLOG_DISABLE_ON_RAW_SAVE = True

# Celery Configuration
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 60  # 1 minute

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'location_erp': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
