# Generated by Django 5.2.10 on 2026-03-01 00:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('caution', models.DecimalField(decimal_places=2, help_text='Montant de la caution/deposit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('resilie', 'Résilié'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('conditions_particulieres', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biens.bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
