# Generated by Django 5.2.10 on 2026-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weather', 'Météo'), ('earthquake', 'Séisme'), ('flood', 'Inondation'), ('other', 'Autre')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
