# Generated by Django 5.2.10 on 2026-03-26 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaireApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invoice_object_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoice_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Connexion reussie'), ('login_failed', 'Connexion echouee'), ('ticket_created', 'Ticket cree'), ('ticket_updated', 'Ticket modifie'), ('ticket_deleted', 'Ticket supprime'), ('invoice_downloaded', 'Facture telechargee'), ('user_created', 'Utilisateur cree'), ('user_updated', 'Utilisateur modifie')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
