# Generated by Django 5.2.10 on 2026-03-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaireApp', '0005_backfill_deliveries_for_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('unused', 'Non utilise'), ('used', 'Utilise'), ('expired', 'Expire')], default='unused', max_length=20),
        ),
    ]
