# Generated by Django 5.2.11 on 2026-03-11 01:07

from django.db import migrations


def make_changes_text_nullable(apps, schema_editor):
    """Rendre le champ changes_text nullable dans auditlog_logentry"""
    db = schema_editor.connection
    
    if db.vendor == 'sqlite':
        # SQLite nécessite de recréer la table
        # D'abord, récupérer la structure actuelle
        with db.cursor() as cursor:
            # Récupérer toutes les colonnes
            cursor.execute("PRAGMA table_info(auditlog_logentry)")
            columns = cursor.fetchall()
            
            # Construire la liste des colonnes pour la nouvelle table
            column_defs = []
            column_names = []
            for col in columns:
                col_name = col[1]
                col_type = col[2]
                not_null = col[3]
                default_val = col[4]
                is_pk = col[5]
                
                column_names.append(col_name)
                
                # Modifier changes_text pour qu'il soit nullable
                if col_name == 'changes_text':
                    col_def = f"{col_name} TEXT"
                elif is_pk:
                    col_def = f"{col_name} {col_type} PRIMARY KEY AUTOINCREMENT"
                elif not_null and col_name != 'changes_text':
                    col_def = f"{col_name} {col_type} NOT NULL"
                else:
                    col_def = f"{col_name} {col_type}"
                
                if default_val is not None and col_name != 'changes_text':
                    col_def += f" DEFAULT {default_val}"
                
                column_defs.append(col_def)
            
            # Créer la nouvelle table
            create_sql = f"CREATE TABLE auditlog_logentry_new ({', '.join(column_defs)})"
            cursor.execute(create_sql)
            
            # Copier les données
            cols_str = ', '.join(column_names)
            cursor.execute(f"INSERT INTO auditlog_logentry_new ({cols_str}) SELECT {cols_str} FROM auditlog_logentry")
            
            # Remplacer l'ancienne table
            cursor.execute("DROP TABLE auditlog_logentry")
            cursor.execute("ALTER TABLE auditlog_logentry_new RENAME TO auditlog_logentry")
            
            # Recréer les index si nécessaire
            cursor.execute("SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name='auditlog_logentry' AND sql IS NOT NULL")
            indexes = cursor.fetchall()
            for idx in indexes:
                if idx[0] and 'auditlog_logentry' in idx[0]:
                    # Recréer l'index avec le nouveau nom de table
                    idx_sql = idx[0].replace('auditlog_logentry', 'auditlog_logentry')
                    cursor.execute(idx_sql)
    else:
        # PostgreSQL et autres
        with db.cursor() as cursor:
            cursor.execute("ALTER TABLE auditlog_logentry ALTER COLUMN changes_text DROP NOT NULL")


def reverse_make_changes_text_nullable(apps, schema_editor):
    """Inverser la migration"""
    db = schema_editor.connection
    
    if db.vendor != 'sqlite':
        with db.cursor() as cursor:
            cursor.execute("ALTER TABLE auditlog_logentry ALTER COLUMN changes_text SET NOT NULL DEFAULT ''")


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('auditlog', '0012_add_logentry_action_access'),  # Dernière migration de django-auditlog
    ]

    operations = [
        migrations.RunPython(make_changes_text_nullable, reverse_make_changes_text_nullable),
    ]
