# Generated by Django 5.2.11 on 2026-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_paiement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='mois_paye',
            field=models.CharField(blank=True, help_text='Mois pour lequel le paiement est effectué (format: YYYY-MM)', max_length=20, null=True),
        ),
    ]
