# Generated by Django 5.2.11 on 2026-03-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_cf0127_idx',
            old_name='notificatio_user_id_lu_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_no_ba8ea8_idx',
            old_name='notificatio_type_no_idx',
        ),
    ]
