# Generated by Django 5.2.10 on 2026-03-01 01:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('import', 'Import'), ('print', 'Impression'), ('email', 'Email envoyé'), ('payment', 'Paiement'), ('contract_sign', 'Signature contrat'), ('contract_terminate', 'Résiliation contrat')], max_length=20, verbose_name="Type d'action")),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='low', max_length=10, verbose_name='Niveau de sévérité')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, max_length=36, verbose_name='ID de requête')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name="Représentation de l'objet")),
                ('action_details', models.JSONField(blank=True, default=dict, verbose_name="Détails de l'action")),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Changements effectués')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['ip_address'], name='audit_audit_ip_addr_685e3f_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('read', 'Lecture'), ('export', 'Export'), ('print', 'Impression'), ('download', 'Téléchargement')], max_length=10, verbose_name="Type d'accès")),
                ('data_type', models.CharField(choices=[('personal_data', 'Données personnelles'), ('financial_data', 'Données financières'), ('contract_data', 'Données contractuelles'), ('payment_data', 'Données de paiement'), ('analytics_data', 'Données analytiques')], max_length=20, verbose_name='Type de données')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('records_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('query_details', models.JSONField(blank=True, default=dict, verbose_name='Détails de la requête')),
                ('export_format', models.CharField(blank=True, max_length=10, verbose_name="Format d'export")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'accès aux données",
                'verbose_name_plural': "Logs d'accès aux données",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_dataa_timesta_07272e_idx'), models.Index(fields=['user', 'timestamp'], name='audit_dataa_user_id_881ffd_idx'), models.Index(fields=['access_type'], name='audit_dataa_access__1f4ac7_idx'), models.Index(fields=['data_type'], name='audit_dataa_data_ty_956816_idx'), models.Index(fields=['ip_address'], name='audit_dataa_ip_addr_f4a9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Échec de connexion'), ('brute_force', 'Attaque par force brute'), ('suspicious_ip', 'IP suspecte'), ('privilege_escalation', 'Escalade de privilèges'), ('data_breach', 'Violation de données'), ('unauthorized_access', 'Accès non autorisé'), ('sql_injection', "Tentative d'injection SQL"), ('xss_attempt', 'Tentative XSS'), ('csrf_attempt', 'Tentative CSRF'), ('rate_limit_exceeded', 'Limite de taux dépassée'), ('suspicious_activity', 'Activité suspecte'), ('security_violation', 'Violation de sécurité')], max_length=30, verbose_name="Type d'événement")),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], max_length=10, verbose_name='Niveau de sévérité')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('investigating', 'En investigation'), ('resolved', 'Résolu'), ('false_positive', 'Faux positif')], default='new', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP source')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_details', models.JSONField(default=dict, verbose_name='Détails de la requête')),
                ('description', models.TextField(verbose_name="Description de l'événement")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails techniques')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notes de résolution')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Événement de sécurité',
                'verbose_name_plural': 'Événements de sécurité',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_secur_timesta_514d2d_idx'), models.Index(fields=['event_type'], name='audit_secur_event_t_92bdc9_idx'), models.Index(fields=['severity'], name='audit_secur_severit_3a342c_idx'), models.Index(fields=['status'], name='audit_secur_status_3760eb_idx'), models.Index(fields=['ip_address'], name='audit_secur_ip_addr_6ccefb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Niveau de log')),
                ('category', models.CharField(choices=[('system', 'Système'), ('database', 'Base de données'), ('api', 'API'), ('auth', 'Authentification'), ('payment', 'Paiement'), ('email', 'Email'), ('backup', 'Sauvegarde'), ('performance', 'Performance'), ('security', 'Sécurité')], max_length=20, verbose_name='Catégorie')),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails techniques')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='Module')),
                ('function', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de ligne')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('request_id', models.CharField(blank=True, max_length=36, verbose_name='ID de requête')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log système',
                'verbose_name_plural': 'Logs système',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_syste_timesta_5ffd22_idx'), models.Index(fields=['level'], name='audit_syste_level_cb3535_idx'), models.Index(fields=['category'], name='audit_syste_categor_40f807_idx'), models.Index(fields=['module'], name='audit_syste_module_60e948_idx')],
            },
        ),
    ]
