# Generated by Django 5.2.10 on 2026-03-01 00:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_depense', models.CharField(choices=[('reparation', 'Réparation'), ('entretien', 'Entretien'), ('taxe', 'Taxe'), ('assurance', 'Assurance'), ('service', 'Service'), ('materiel', 'Matériel'), ('autre', 'Autre')], max_length=20)),
                ('facture', models.FileField(blank=True, null=True, upload_to='factures/')),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biens.bien')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depenses.categoriedepense')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
