# Generated by Django 5.2.11 on 2026-03-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_type_do_b36790_idx',
            old_name='documents_d_type_do_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_bien_id_feb388_idx',
            old_name='documents_d_bien_id_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_client__75b1a2_idx',
            old_name='documents_d_client__idx',
        ),
    ]
