# Generated by Django 5.2.10 on 2026-03-18 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescuerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('revoked', 'Révoqué')], db_index=True, default='pending', max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('diploma_type', models.CharField(blank=True, max_length=64)),
                ('proof_storage_key', models.CharField(blank=True, max_length=512)),
                ('proof_original_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescuer_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
