# Generated by Django 5.2.10 on 2026-03-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_indicateur', models.CharField(choices=[('roi', 'ROI'), ('cashflow', 'Cashflow'), ('occupation', 'Taux occupation'), ('revenu_moyen', 'Revenu moyen'), ('depense_moyenne', 'Dépense moyenne')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Indicateur de performance',
                'verbose_name_plural': 'Indicateurs de performance',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('depenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_occupation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nombre_biens_loues', models.IntegerField(default=0)),
                ('nombre_biens_total', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('annee', 'mois')},
            },
        ),
    ]
