# Generated by Django 5.2.10 on 2026-03-01 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('telephone', models.CharField(help_text='Format: +221 77 123 45 67', max_length=20, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone n'est pas valide.", regex='^\\+?[\\d\\s-]{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.TextField()),
                ('piece_identite', models.CharField(help_text='CNI, Passeport, etc.', max_length=50)),
                ('numero_piece_identite', models.CharField(blank=True, max_length=50, null=True)),
                ('defaut_paiement', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
