# Generated by Django 5.2.10 on 2026-03-01 00:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiel', 'Partiel'), ('paye', 'Payé'), ('en_retard', 'En retard'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_echeance'],
            },
        ),
    ]
